#!/bin/bash

# helper script to execute a program on every box in a netgroup

# make sure netgroup supplied
if [[ $# -lt 1 ]] ; then 
    echo 'must supply netgroup (at least)'
    exit
fi

group=$1

# remove the group argument, since it shouldn't be passed to fzrun
set -- "${@:1:}" "${@:2}"

# netgrouplist fails silently if invalid netgroup provided. 
if [[ -z $(netgrouplist $group) ]] ; then
    echo "empty netgrouplist. Possible typo with '$group' ?" > /dev/stderr
    exit 255
fi

# parallelize over entire set of boxen in netgroup
netgrouplist $group \
| xargs -I '{}' -P 0 \
ssh -o StrictHostKeyChecking=no  '{}' $@ 2>/dev/null 